.TH jk_socketd 8 10-05-2004 JAILKIT jk_socketd

.SH NAME
jk_socketd \- a daemon to safely create /dev/log inside a chroot

.SH SYNOPSIS

.B jk_socketd

.B jk_socketd -p
.I pidfile
.B -n

.B jk_socketd --pidfile=
.I pidfile
.B --nodetach

.SH DESCRIPTION

The jailkit socket daemon creates a /dev/log socket inside a jail according to 
.I /etc/jailkit/jk_socketd.ini
and writes all data eventually to syslog using the real
.I /dev/log
Programs like jk_lsh and also many daemons need a /dev/log socket to do logging to syslog.

Why not have syslog create the socket inside your jail? jk_socketd can limit the number of bytes written trough the socket. The rate limiting is done based on three parameters, the base, the peek and the interval. The interval is the number of seconds that jk_socketd will use to count up to the number of bytes. The base and peek are both a number in bytes.

A socket is normally only allowed to have base bytes going trough per interval seconds. Only if in the previous interval the number of bytes has been lower than base, peek number of bytes is allowed. So a peek can only happen if the previous interval has been lower than base.

The config file consists of several entries where each entry looks like this:

.nf
.sp
[/home/testchroot/dev/log]
base = 512
peek = 2048
interval = 10
.fi

The title of the section is the socket to be created. The directory to create the socket in should exist.

.SS "Security"
The jailkit socket daemon will change to user nobody and will chroot() into an empty dir once all sockets are opened.

.SH OPTIONS
.TP
.BR \-n\ \-\-nodetach
do not detach from the terminal and print debugging output
.TP
.BR \-p\ pidfile\ \-\-pidfile=pidfile
write PID to pidfile
.TP
.BR \-h\ \-\-help
show help screen

.SH FILES

.I /etc/jailkit/jk_socketd.ini

.SH DIAGNOSTICS

jk_socketd logs errors to syslog, so check your log files

otherwise run jk_socketd -n and it will not detach from the terminal, and it will print some debugging output. 

.SH "SEE ALSO"

.BR jailkit(8)
.BR jk_check(8)
.BR jk_chrootlaunch(8)
.BR jk_chrootsh(8)
.BR jk_cp(8)
.BR jk_init(8)
.BR jk_lsh(8)
.BR jk_procmailwrapper(8)
.BR syslogd(8)

.SH COPYRIGHT

Copyright (C) 2003, 2004, 2005, Olivier Sessink

Copying and distribution of this file, with or without modification,
are permitted in any medium without royalty provided the copyright
notice and this notice are preserved.
